'use client';

import { FiFileText, FiSearch, FiFilter } from 'react-icons/fi';

export default function AgreementManagement() {
  return (
    <div className="space-y-6">
      <div className="pb-5 border-b border-gray-200">
        <h1 className="text-3xl font-extrabold leading-tight text-[#232F3E]">Agreement Management</h1>
        <p className="text-sm text-gray-500 mt-1">Review legal documents, contract signatures, and terms generated by farmers.</p>
      </div>

      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
        <div className="p-6 border-b border-gray-100 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div className="relative flex-1 max-w-md">
            <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-gray-400">
              <FiSearch className="h-5 w-5" />
            </span>
            <input
              type="text"
              placeholder="Search agreements by ID or party..."
              className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1A9B9A] focus:border-transparent text-sm"
              disabled
            />
          </div>
          <div className="flex items-center gap-2">
            <button className="flex items-center gap-2 px-4 py-2 border border-gray-200 rounded-xl text-gray-600 hover:bg-gray-50 text-sm font-semibold transition-colors" disabled>
              <FiFilter /> Filter
            </button>
          </div>
        </div>

        <div className="p-12 text-center text-gray-500">
          <div className="mx-auto w-12 h-12 bg-[#E6F7F7] text-[#1A9B9A] rounded-xl flex items-center justify-center mb-4">
            <FiFileText className="h-6 w-6" />
          </div>
          <h3 className="text-lg font-bold text-[#232F3E] mb-1">Agreement Management Foundation</h3>
          <p className="text-sm text-gray-500 max-w-md mx-auto">This module will list all system generated PDF contracts, signatures, and status logs in the next phase.</p>
        </div>
      </div>
    </div>
  );
}
